services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
      POSTGRES_DB: catalog
    ports:
    - "5432:5432"

  catalog:
    build: ./apps/catalog
    environment:
      DATABASE_URL: postgresql://catalog:catalog@postgres:5432/catalog
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  cart:
    build: ./apps/cart
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8001:8000"
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  orders:
    build: ./apps/orders
    environment:
      DATABASE_URL: postgresql://catalog:catalog@postgres:5432/catalog
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8002:8000"
    depends_on:
      - postgres
      - rabbitmq

  worker:
    build: ./apps/worker
    environment:
      DATABASE_URL: postgresql://catalog:catalog@postgres:5432/catalog
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
