server {
    listen 80;

    # Отдаём статику (нашу страницу)
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Проксируем /api/* на сервис catalog
    location /api/ {
        proxy_pass http://catalog:8000/;
    }
}
