---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgCzMOCgQ6BTBW/rFoLvAHeFi7p8omZULLGMZAqw9KU4seOKyeSt4+4JOJzojLKiCzWPCNWDtrI6qsC1j2z2H22wQzvZa4A4sT5oDOTCNe/HZu0MSXJF25e24Laer3wOQaorYDj156vqJvUrGFFcrIBeAdRr685d1+udrhAhoK0YrSxiEIQn1czpRprK4IgBk86DGdbYcgfG1AIOiFV3tOKMNF18QxIn+CtcyAcd5qT9seeuhDgnbG2LqNGeUIqfY94H3ylAb9u4ZbDkYwQoSuq8hRSs/2jDScG5ZJxMgH7lKPudkWdmtvFZes5TqN62lhvrVeN94hP58jDsYHvAcvAL0oCComwBGOqVaST5tMYg/PeZERlRFp4yrDXyTKSZaqtCglSGfwmWAMJKAWjY2tzvvYwaVtP4pobsAvQmKDb0JWek0vdMpOVUVrh4sFLvpbHOO4ldsgUO/127Y9D8+YcErZRYWDOnZfJfub79mSdvldYKegc+CpGh3qIJvNWz/5K94C7pnFe/MzFSPNGgIbEssiVUUNFPllqSMHUA9gxCwy6SJXbASdvUpBfgy8Cxpd3l8dIeGYusfD5wG/XCLbGG5sYPi2xUCJkoV1B4oyWmmB/z4LnGxeXQUvAxvgHxA8Blf6/evMZlXG21SqB6dj8V20aDm9xhfcT0iwx3VMFWk73Y9J2+Opjf/Z3RSlUjzFz9ZnHPreqOx58uLEy1j1MktPwe7ocdNQy9drjAaTMgPf09/Oqk/CdUzYej32+Ld15BOQ==
    RABBITMQ_URL: AgBq6PAza/vADLRGv8xQPRUqUFuR53/t19VPtbwc86L5xrncJZY733NOT9pHwDISOEW6ctSj3L3VK1UibSQYaHqveNqWJGKvCAMT3gkmIvmYI1rtz6q3uiUJReSpJz6PKdt8a9RRCou5MGIc1GcTv5HLYUrihYzDmm5ICfCCmveGeXiO0xQ9454htahhLy3MvfLPSTQzD7zKNZh4qKI3ICNEdDOVsrLbGyp2+SRAomcnaISSKuJ3ruUHA1EDrgqOPtgL94zNRCvmISdRoL3NY3qnowatxenyovw+rZkE8Kdq5wYrwjbPChKRbyo8qZWOVaqthKEnJziuGvXgd+dW5YhP4LazSVuFqCUvLnfBe/lwc2znEdj7UVJ5dqRuBSmCKT8cRdWJAKugD63J/+KD7Bfd0ssaGt+jiOypeugA43h7qFspSmK6IzggbhJudUnftFNvFnk4xY8kimM8BgwJZBAUhPAdUlb0bnZrjwyFIHbO2Oxb1nDygIEjl8sTZ2VlP6hg7BkXR0XsbQhm3awMEPXSUzDbTxv6LlC+ihR1PanfZnZeenTF5FtY5RxL2uEtKP0yLsVhXQkFY+WFERsdVl13baJc5e3YbVnEh0jPtqrZwHfNPQDXswqShB5JnkXlRGLOtpdE4P7leV6mugoqeOb5Az0q7t8b/mp80iIxEsSx3AEfgG68HqSY6akxepcvgspCuZzbzuaFmgi6yKicDqDM74BhXt55xfu1EsdM7+O5vjs=
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: default
    type: Opaque
