---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgAKmrMVCQu8fWdWmpoi0M8CYHv++lPcFy3r5S9T+GBg5t9KV56fGG70SYin6lQbontQMIhDU76avXsJSpMtKWi9TD9TLRhtwBLwE171jzmXYrYAaIGuNDGT1UdJ2fuKgl50B/4BABhNiv38UJ7OK5aCXY9ydHM1KaPtPZccHTaNiPAf97YEmbQVUKvpOKGgFrDwZutI5QnQxOOXScj8IIQHiAPWOUUNfG2NSR85TfGriaJoqUwo0ec+TVSLzOvq03yFCrXNA8k8hnNiT/6ncEfmNZOtWcrTLz5IWNRLK5SBfDxyyAHgTtIbV3PZu+/6JQAjm9owX/HWy2A3j89qHCrz22zt01Nu3hc11n2MfDfPBAKiounPe0qc1A2sZsdgeZ+v6OeuaTKYHQQSMdHnEM0WXSJ3dSSEPsFk+2gyri+hMe1nf/TL3czh2ZxIkxfTBuAQlz6lDOaBMiwRYQqdm9EwkZUaRLxrrdcueqZUupMIUxaHsluZdCM+gabPpLEh8bDYRqp2d4rWV40N2V0ucFe4CO0DPSJ3uCC1bjAsevagxKBRraqLsLO9uGqYWKk8mt1vmdvKiTxnG8pPAecM6AipJS/zUgp6ahGpAaiOk8KP95mahZZKxseLOEKujIlmC9JAoi3hAhMRdvzO0o4SxKvm5h7PsJjkqqLiB785/Uccw7/d9HIOztMpiUXZTX5rlwx187qa3Hr0C/nDqIAQip/jkKLKc0htC9v0MmWsTXBBLVYctvwgIX5D6OPpi9xVOI2L8A==
    RABBITMQ_URL: AgAIFhSwUnqYVhL6StS66cTne5ojTZZWJhP6PjbCo3HvJ5kwGCuOaXbWcE32PgSeB6IMUPILo7O67xSqiMVvLCa+SXeF76LKyFMITdDsONWMz3Lrtzk7tlOy5judW/4JsImEkPf5Vub6r67WdQzA7Sy9axpxAI/A6y4Lantsepox8MCdLjjr3L1SIErA/YqhuHf/YqUO0FTIJsYYjJouhzWFujQNGJmps/FO+VvY/7gea+ZaSi6VRSx+6P2rracfvAG14q9oygJ/Lv+Jqs2AyU6V4ZoX2VcyEwTrHyLa22XUS57kw+7D0aThWUeNEdxSoX7AVUZHaQoBrLNrVfLp7/q3BlPb+PO24T1yT6tZ5qSu39Oy2mTjBgh/WwS4xPvb8pB2/IhfJ00Hu7iQDjp6yZoCOeLMlFK56715Y1sgwXBK1Emt2/SGtR6ZAoiGrugOTWeAG7KWen8PrIn8gXLmm4YqqGi02+5fGErI3fK9JKncNOUcw0M5h33WrlTaX1SawvddUbf7QjV+cUv+KiA0vOzEIyW6E+n8nkkAwe3rW8q3xeov1M5vBS6uce0lY269pJHUtKreCs0+/juidWo223WGiX5G3HrYiTz6Z3kBwPx13oOV/ZJQfsEowqhv99Opr32vetkvGUEj9ZBs1TlbI0juk7/GvMpheRa7j8J4O8Ye1ZKgOkvHMNofx2jldsxpCVucgBMKCI38pKTbE8/2VdIyEETwWgxT5d/PxpCZylSloKc=
  template:
    metadata:
      creationTimestamp: null
      name: app-secret
      namespace: default
    type: Opaque
