---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAWepuqxtzwSeu/2ZYq8rM2WtG/sZAyJPU1R57m/52oKHoHEf2udvgOBZruXEJTZfoMHYAeFX137sQsDkleojx8rr6XFZ5OtAoYHWkxaTlmGXOZK0OsgF+05l8p3lrYwNh/p3WEnyq3wCDMBfezzYs9+vBV3+DEf3H80Lwa6aLqbWGD5XXWS4IJdXHuBFG9FOi01uATMVUYzC0aLchYaLNQRaQJiNVMGipUUQbXULjH8uw79Vj5IgyD+N3WCtXh/uWWTULVWA/J5tjcHTW9jzNfQjOt5qPBnbbpzighHXlt7MSijmSV11yS9BgATyzqIfJeYhz17xBuCI/lZAMUAGwaWuQACvFb2/kkxzqNaMX/5C+mFghTruHosdPHzgmA6db5dfZlc6rqj6aysqbr6HTi+oP1m+mxNu69XdKXXMo4E+sSnxDnod/csRQUiY7+SW9n8omeKHt2tG8+PtuKZvRWYbMCodX9YozfNSF9F64ei7+u02TmTttCpKgoqXPqdy/fmicLYkTihatJH1qibE6HB3ZkHoMa7pHP1CnuWF7nzO+ABgaZKTgWS+d/Y4kaL1gLmBZIHhYqbz8gBt1xVeW5Ndq/7pXvh05CboxBC081LI6nqCug7aCh4p/9rWwueJQZztCrcPurTtnoYohseR4/EHsY357xubsWx2OoA0W6aREjn23ap3dB32/C3aETtLjkUX0gy8Mt
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default
    type: Opaque
