---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBy/58QTgPNIqMPzD8ENevnuUXsRX/ylp8uMlKAapWZHfNQiOEM5SRUccS3zhBmiOGWDp94BV8oFr/KwmcwoPTeDk2Xyl9OgDw5LN/twCBqPOyPZARbdVG7RhUC3K6c8+LKSu7j49rMvdPl4upDEpuF/bpaj8gnCS8kJOHHiBmvgJKhxl07ndojP23DLBvwaZn4w9+eFN/GUxlhwW51vE0hYeOqSoGEiY0XWrsfCdH5nn8Z5IzS1cMZpTsRLBgwbIS9YPqYGefQcL38g2wgt82gyR428FsixpqhX4+3vLMeQD171cXj0udQuoeYFzMzvOLxRY0pA22f8xAm1NvrfBv3RP4K9P/oefd+1PsxVaw2if7U8sPjxQCuPWWeiAV3qA+qTGviDLxpOTxo80VxgL0NG0Pt1A0eyr1jpVvhTcgQl5Mdnhwv+nMq8UrciGZoCqsJ1zGkQ9NYfaKPV3H5/M0MoHP0gkaUwvYfYweJKKftS+Lnz2KhOw+Sylll+RcK6axIHqiQYRUPLRdSY0AdFrv0YiNtMUWMEvip1QMC1GE3MpXKjzpkcbtI7lU26GvWnD6Vgfc3/YXRvJZzeyp7yriGYyK94EPIaD7zSHV3ghFxEwnr0ouaG73Yg1ZJjo3SYOYaYxHXrIvpDQLVtTijWYPy+Yjq9Ltonm3pYt5DMfmFbZJgpbyv/rn/xWjCA7SCp5INvWYfNrAS
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: default
    type: Opaque
